### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Mick9555** [RedDeadDepresso/BAAuto#7]
idk what i am doing can you help me do it by using anydesk app ?

**Comment by RedDeadDepresso** [comment]
Hi, I don't think it would be safe to use remote access for privacy and security reasons. If you have problems running the program, describe the problem and, if possible, paste the contents of traceback.log. If you have trouble following the instructions on README.md, I will try to explain them here in great detail. 

1. Install an android emulator, preferably [Bluestacks 5](https://www.bluestacks.com/bluestacks-5.html) .
2. Change the resolution to 1280x720 and enable ADB https://support.bluestacks.com/hc/en-us/articles/360053245871-How-to-use-the-BlueStacks-5-Settings-menu
3. Install Blue Archive from the play store
4. Install Python https://www.python.org/downloads/ and remember to check the box "Add python to environment variables"
5. Download adb and add to path https://www.youtube.com/watch?v=OSp5_wBAVyQ
6. Finally, open the command prompt and type "cd path/to/BAAuto"  and press Enter
7. then type "pip install -r requirements.txt". This will install the python libraries.
8. Run BAAuto and in connection address type the emulator IP:PORT e.g 127.0.0.1:5557
9. Configure the rest however you like and click the start button while the emulator is running

I hope these instructions are comprehensive, but if you are still having problems I will try to help you. Please note that the GUI has some bugs and I'm trying to fix them.

**Comment by Mick9555** [comment]
i have a learning disapility so can you just add me on discord and use Anydesk

**Comment by RedDeadDepresso** [comment]
I'm sorry, I don't want to take risks. You can ask friends and family for help. You honestly won't miss much as the script only saves you 5 minutes a day at most and it doesn't automate all the tasks like Lessons.
